version: "2"
services:
  service:
    build:
      context: .
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bd_ceoak_v2
    volumes:
      - $HOME/www/data/postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"
# volumes:
#   dbdata:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "$HOME/www/data/postgres-data"
