version: "3.8"
services:
  service:
    build:
      context: .
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bd_ceoak_v2
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/vinic/www/data/postgres-data"
